CREATE TABLE HR(id SERIAL, question TEXT);
INSERT INTO HR(question) VALUES ('Tell me about yourself.'),
('What motivates you?'),
('How do you evaluate success?'),
('What has been the greatest disappointment in your life?'),
('What do people most often criticize about you?'),
('What is your greatest weakness?'),
('What is your greatest strength?'),
('What type of work environment do you prefer?'),
('Describe a difficult work situation/project and how you overcame it.'),
('What has the most satisfying moment in your life been?'), 
('What types of hobbies do you enjoy outside of work?'),
('What is your greatest fear?');

CREATE TABLE casual(id SERIAL, question TEXT);
INSERT INTO casual(question) VALUES ('A useless talent that you have?'), 
('One food item you can eat everyday?'), 
('The last time you said sorry to someone?'), 
('Your favourite memory from school till now?'), 
('One advice your parents have given you that you always keep in mind?'), 
('One thing you wish to do to make the world a better place?'), 
('Your best friend forever?'), 
('One thing which can easily piss you off?'), 
('Your icon?'), 
('The person who calls you the most?'), 
('A song that you are humming these days?'), 
('The last show you binge watched?'), 
('The coolest thing you have ever done?'), 
('The scariest thing you have ever done?'), 
('Your favourite dish?'), 
('Your ultimate inspiration?'), 
('Your biggest fear?'), 
('If you had to make a tatto right now what will it be?'), 
('The last time you cried and why?'), 
('Where do you see yourself in next 5 years?'), 
('One thing which can bring a smile on your face?'); 